-- A narrow public event stream lets open frontend pages refresh without
-- exposing protected CMS rows (especially site_settings) through Realtime.
create table if not exists public.cms_refresh_events (
  id bigint generated by default as identity primary key,
  scope text not null default 'site',
  created_at timestamptz not null default now()
);

alter table public.cms_refresh_events enable row level security;

drop policy if exists "public read cms refresh events" on public.cms_refresh_events;
create policy "public read cms refresh events"
  on public.cms_refresh_events
  for select
  using (true);

grant select on table public.cms_refresh_events to anon, authenticated;

do $$
declare
  cms_table text;
  cms_tables text[] := array['cms_refresh_events'];
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    foreach cms_table in array cms_tables loop
      if to_regclass(format('public.%I', cms_table)) is not null
        and not exists (
          select 1
          from pg_publication_tables
          where pubname = 'supabase_realtime'
            and schemaname = 'public'
            and tablename = cms_table
        )
      then
        execute format(
          'alter publication supabase_realtime add table public.%I',
          cms_table
        );
      end if;
    end loop;
  end if;
end
$$;

-- Expose only public-facing settings through a controlled RPC. The underlying
-- table remains protected by RLS and the integrations object is not returned.
create or replace function public.get_public_site_settings()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select to_jsonb(settings_row) - 'integrations'
      from public.site_settings as settings_row
      order by settings_row.updated_at desc nulls last
      limit 1
    ),
    '{}'::jsonb
  );
$$;

revoke all on function public.get_public_site_settings() from public;
grant execute on function public.get_public_site_settings() to anon, authenticated;

create or replace function public.emit_cms_refresh_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  refresh_id bigint;
begin
  insert into public.cms_refresh_events (scope)
  values (tg_table_name)
  returning id into refresh_id;

  delete from public.cms_refresh_events
  where id < refresh_id - 1000;

  return null;
end;
$$;

revoke all on function public.emit_cms_refresh_event() from public;

do $$
declare
  cms_table text;
  cms_tables text[] := array[
    'site_settings',
    'page_heroes',
    'page_content_sections',
    'pages',
    'safari_packages',
    'destinations',
    'experiences',
    'reviews',
    'homepage_sections',
    'homepage_quick_links',
    'homepage_trust_items',
    'homepage_features',
    'homepage_guide_articles',
    'gallery_media'
  ];
begin
  foreach cms_table in array cms_tables loop
    if to_regclass(format('public.%I', cms_table)) is not null then
      execute format(
        'drop trigger if exists cms_emit_refresh_event on public.%I',
        cms_table
      );
      execute format(
        'create trigger cms_emit_refresh_event after insert or update or delete on public.%I for each statement execute function public.emit_cms_refresh_event()',
        cms_table
      );
    end if;
  end loop;
end
$$;
